&lt;html&gt;
&lt;head&gt;
&lt;title&gt;Simple 2D Dropping Menu&lt;/title&gt;
&lt;link   rel = "stylesheet"  href = "Simple2DDroppingMenu.css"&gt;
&lt;script src = "jquery-1.11.3.min.js"&gt;&lt;/script&gt;
&lt;script src = "Simple2DDroppingMenu.js"&gt;&lt;/script&gt;
&lt;script src = "myvidget.js"&gt;&lt;/script&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;ul id="my_menu"&gt;
&lt;li&gt; 
&lt;a  href="#"&gt;Home&lt;/a&gt;
&lt;/li&gt;
&lt;li&gt; 
&lt;a href = "#"&gt;Menu 1&lt;/a&gt; 
&lt;ul&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 1&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 4&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 5&lt;/a&gt;&lt;/li&gt; 
&lt;/ul&gt; 
&lt;/li&gt; 
&lt;li&gt; 
&lt;a  href="#"&gt;Menu 2&lt;/a&gt; 
&lt;ul&gt;
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-1&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-2&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-3&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-4&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-5&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-6&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-7&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 2-8&lt;/a&gt;&lt;/li&gt; 
&lt;/ul&gt; 
&lt;/li&gt; 
&lt;li&gt; 
&lt;a href="#"&gt;Menu 3&lt;/a&gt; 
&lt;ul&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3-1&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3-2&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3-3&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3-4&lt;/a&gt;&lt;/li&gt; 
	&lt;li&gt;&lt;a href="#"&gt;Submenu 3-5&lt;/a&gt;&lt;/li&gt; 
&lt;/ul&gt; 
&lt;/li&gt; 
&lt;/ul&gt;
&lt;/body&gt;
&lt;/html&gt;

